from pathlib import Path

import pandas as pd
import requests
import streamlit as st


# ==========================================================
# PAGE CONFIGURATION
# ==========================================================

st.set_page_config(
    page_title="Insurance Pricing PoC",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="expanded",
)

BASE_DIR = Path(__file__).resolve().parent

ML_API_URL = "http://127.0.0.1:8000"
JAVA_API_URL = "http://127.0.0.1:8080"

REFERENCE_DATA_PATH = (
    BASE_DIR / "pricing_reference.csv"
)

CONTRIBUTION_IMPORTANCE_PATH = (
    BASE_DIR / "contribution_feature_importance.csv"
)

EXPENSE_IMPORTANCE_PATH = (
    BASE_DIR / "expense_feature_importance.csv"
)


# ==========================================================
# STYLING
# ==========================================================

st.markdown(
    """
    <style>
        .block-container {
            max-width: 1200px;
            padding-top: 2rem;
            padding-bottom: 3rem;
        }

        .hero {
            padding: 2rem 2.2rem;
            border-radius: 18px;
            background: linear-gradient(
                135deg,
                #062f57 0%,
                #0b67b2 100%
            );
            color: white;
            margin-bottom: 1.5rem;
        }

        .hero h1 {
            color: white;
            margin: 0;
            font-size: 2.35rem;
        }

        .hero p {
            color: #eaf4fc;
            margin-top: 0.7rem;
            margin-bottom: 0;
            font-size: 1.05rem;
            max-width: 850px;
        }

        .result-card {
            background-color: #f4f8fc;
            border: 1px solid #bdd4e8;
            border-radius: 14px;
            padding: 1.25rem;
            min-height: 165px;
        }

        .result-label {
            color: #425466;
            font-size: 0.95rem;
            font-weight: 650;
        }

        .result-value {
            color: #07345e;
            font-size: 1.9rem;
            font-weight: 750;
            margin-top: 0.35rem;
        }

        .result-note {
            color: #5c6d7d;
            font-size: 0.88rem;
            margin-top: 0.55rem;
        }

        div[data-testid="stButton"] > button {
            min-height: 3.2rem;
            border-radius: 10px;
            font-weight: 700;
            font-size: 1rem;
        }

        div[data-testid="stMetric"] {
            border: 1px solid #e0e7ee;
            border-radius: 12px;
            padding: 1rem;
            background-color: white;
        }
    </style>
    """,
    unsafe_allow_html=True,
)


# ==========================================================
# DATA-LOADING FUNCTIONS
# ==========================================================

@st.cache_data
def load_optional_csv(path):
    """
    Load a CSV if it exists.

    These files are generated by training.py and are used
    only for visual explanations in the Streamlit app.
    """

    if not path.exists():
        return None

    return pd.read_csv(path)


reference_data = load_optional_csv(
    REFERENCE_DATA_PATH
)

contribution_importance = load_optional_csv(
    CONTRIBUTION_IMPORTANCE_PATH
)

expense_importance = load_optional_csv(
    EXPENSE_IMPORTANCE_PATH
)


# ==========================================================
# API FUNCTIONS
# ==========================================================

def check_ml_api():
    """Check whether the Python ML service is available."""

    try:
        response = requests.get(
            f"{ML_API_URL}/health",
            timeout=3,
        )

        response.raise_for_status()
        return True, response.json()

    except requests.RequestException:
        return False, None


def check_java_api():
    """
    Check whether the Java backend is reachable.

    A 404 response still proves that the Spring server is
    running because the application may not define a root route.
    """

    try:
        response = requests.get(
            JAVA_API_URL,
            timeout=3,
        )

        return True, response.status_code

    except requests.RequestException:
        return False, None


def call_treatment_contribution_api(
    age,
    bmi,
    children,
    gender,
    discount_eligibility,
    region,
    treatment_cost,
):
    """Request a treatment-contribution prediction."""

    payload = {
        "age": int(age),
        "bmi": float(bmi),
        "children": int(children),
        "gender": gender,
        "discount_eligibility": (
            discount_eligibility
        ),
        "region": region,
        "treatment_cost": float(
            treatment_cost
        ),
    }

    response = requests.post(
        (
            f"{ML_API_URL}/predict/"
            "treatment-contribution"
        ),
        json=payload,
        timeout=30,
    )

    response.raise_for_status()
    return response.json()


def call_policy_illustration_api(
    age,
    bmi,
    children,
    gender,
    discount_eligibility,
    region,
    expected_treatments_per_year,
    administration_rate,
    uncertainty_rate,
    margin_rate,
):
    """Request an illustrative policy price."""

    payload = {
        "age": int(age),
        "bmi": float(bmi),
        "children": int(children),
        "gender": gender,
        "discount_eligibility": (
            discount_eligibility
        ),
        "region": region,
        "expected_treatments_per_year": float(
            expected_treatments_per_year
        ),
        "administration_rate": float(
            administration_rate
        ),
        "uncertainty_rate": float(
            uncertainty_rate
        ),
        "margin_rate": float(
            margin_rate
        ),
    }

    response = requests.post(
        (
            f"{ML_API_URL}/predict/"
            "policy-illustration"
        ),
        json=payload,
        timeout=30,
    )

    response.raise_for_status()
    return response.json()


def extract_api_error(error):
    """Return a readable error message from an API failure."""

    if error.response is not None:
        try:
            response_body = error.response.json()

            if "detail" in response_body:
                return str(
                    response_body["detail"]
                )

            return str(response_body)

        except ValueError:
            return error.response.text

    return str(error)


# ==========================================================
# DISPLAY HELPERS
# ==========================================================

def format_label(value):
    """Convert stored values into readable labels."""

    return (
        str(value)
        .replace("_", " ")
        .title()
    )


def get_bmi_category(bmi):
    """Return a descriptive BMI band."""

    if bmi < 18.5:
        return "Underweight"

    if bmi < 25:
        return "Healthy range"

    if bmi < 30:
        return "Overweight"

    return "Obese range"


def display_customer_form(
    form_key,
    button_text,
    include_treatment_cost=False,
):
    """Display shared customer-input fields."""

    with st.form(form_key):
        column_1, column_2, column_3 = (
            st.columns(3)
        )

        with column_1:
            age = st.number_input(
                "Age",
                min_value=18,
                max_value=100,
                value=35,
                step=1,
                key=f"{form_key}_age",
            )

            gender = st.selectbox(
                "Gender",
                ["male", "female"],
                format_func=format_label,
                key=f"{form_key}_gender",
            )

        with column_2:
            bmi = st.number_input(
                "Body mass index (BMI)",
                min_value=10.0,
                max_value=70.0,
                value=27.5,
                step=0.1,
                key=f"{form_key}_bmi",
            )

            children = st.number_input(
                "Number of children",
                min_value=0,
                max_value=20,
                value=0,
                step=1,
                key=f"{form_key}_children",
            )

        with column_3:
            discount_eligibility = st.selectbox(
                "Discount eligible",
                ["no", "yes"],
                format_func=format_label,
                key=f"{form_key}_discount",
            )

            region = st.selectbox(
                "Region",
                [
                    "northeast",
                    "northwest",
                    "southeast",
                    "southwest",
                ],
                format_func=format_label,
                key=f"{form_key}_region",
            )

        treatment_cost = None

        if include_treatment_cost:
            treatment_cost = st.number_input(
                "Hospital treatment cost",
                min_value=1.0,
                max_value=1_000_000.0,
                value=10_000.0,
                step=100.0,
                format="%.2f",
                help=(
                    "Enter the amount requested by the "
                    "hospital for the treatment."
                ),
                key=f"{form_key}_cost",
            )

        submitted = st.form_submit_button(
            button_text,
            type="primary",
            use_container_width=True,
        )

    return {
        "submitted": submitted,
        "age": int(age),
        "bmi": float(bmi),
        "children": int(children),
        "gender": gender,
        "discount_eligibility": (
            discount_eligibility
        ),
        "region": region,
        "treatment_cost": treatment_cost,
    }


def display_result_card(
    label,
    value,
    note,
):
    """Display a consistent result card."""

    st.markdown(
        f"""
        <div class="result-card">
            <div class="result-label">
                {label}
            </div>
            <div class="result-value">
                {value}
            </div>
            <div class="result-note">
                {note}
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def show_feature_chart(
    importance_data,
    title,
):
    """Display model feature importance if available."""

    st.subheader(title)

    if (
        importance_data is None
        or importance_data.empty
    ):
        st.info(
            "Feature-importance information is unavailable. "
            "Run training.py again to generate it."
        )
        return

    chart_data = (
        importance_data
        .head(10)
        .set_index("feature")[["importance"]]
    )

    st.bar_chart(
        chart_data,
        horizontal=True,
        color="#2167d5",
    )

    st.caption(
        "This chart shows overall model importance across "
        "the training dataset. It does not prove that an "
        "individual feature caused a particular result."
    )


# ==========================================================
# SESSION STATE
# ==========================================================

if "claim_result" not in st.session_state:
    st.session_state.claim_result = None

if "policy_result" not in st.session_state:
    st.session_state.policy_result = None


# ==========================================================
# HEADER
# ==========================================================

st.markdown(
    """
    <div class="hero">
        <h1>Insurance Pricing Proof of Concept</h1>
        <p>
            Estimate an existing policyholder's contribution
            towards hospital treatment, or create an illustrative
            annual policy price using expected treatment costs
            and transparent pricing assumptions.
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)


# ==========================================================
# SERVICE STATUS SIDEBAR
# ==========================================================

ml_available, ml_health = check_ml_api()
java_available, java_status = check_java_api()

with st.sidebar:
    st.header("Service status")

    if ml_available:
        st.success("ML API is running")

        if ml_health:
            if ml_health.get(
                "contribution_model_loaded"
            ):
                st.caption(
                    "Treatment model loaded"
                )

            if ml_health.get(
                "expense_model_loaded"
            ):
                st.caption(
                    "Expense model loaded"
                )
    else:
        st.error("ML API is not running")

        st.code(
            (
                "python -m uvicorn "
                "ml_api:app --reload --port 8000"
            ),
            language="powershell",
        )

    if java_available:
        st.success(
            "Spring Boot backend is running"
        )
    else:
        st.warning(
            "Spring Boot backend is not currently reachable"
        )

        st.code(
            "mvn spring-boot:run",
            language="powershell",
        )

    st.divider()

    st.header("Application overview")

    st.markdown(
        """
        **Treatment contribution**

        Estimates how much an existing policyholder pays
        towards a hospital treatment.

        **Policy illustration**

        Estimates expected treatment costs and applies visible
        pricing assumptions to produce annual and monthly
        illustrative prices.
        """
    )
